### ISSUE TITLE
theforeman.foreman.content_view_filter unable to create rules

### ISSUE THREAD

**Issue by Siddhu1096** [theforeman/foreman-ansible-modules#1372]
##### SUMMARY

theforeman.foreman.content_view_filter is unable to create rules. It says the 3 other packages with the same name found even though we have specified the correct content view and product name. Raising the issue here as directed from community portal of foreman. For reference - https://community.theforeman.org/t/how-to-give-repositories-input-in-content-view-filter/27993/5?u=almond

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
```

##### COLLECTION VERSION

```

```

##### KATELLO/FOREMAN VERSION

```
foreman-3.1.0-1.el8.noarch
```

##### STEPS TO REPRODUCE

Run the below yaml file after creating multiple products and their content views

```
  - name: my_filter
    theforeman.foreman.content_view_filter:
      username: "admin"
      password: "admin"
      server_url: "myhost"
      name: "package filter 1"
      organization: "COT"
      content_view: "Test_Alma84"
      filter_type: "package_group"
      rule_name: "Core"
      repositories:
        - name: BaseOS
          product: Almatest_84

```

##### EXPECTED RESULTS

The expected results is to create filter "package_filter_1" and add "Core" as package_filter rule
##### ACTUAL RESULTS

But in our case we are getting an error saying 4 more results are found in the same name even after adding content view and product name. 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Found too many (4) results while searching for package_groups with name=\"Core\""}
```

**Comment by parmstro** [comment]
This issue may be considered resolved with the release of v3.9.0

**Comment by killroy1971** [comment]
Unfortunately, it wasn't resolved. I'm running ansible 2.9 with the v3.9.0 foreman collection. The "Core" repo only appears once in the RHEL 8 BaseOS repository.

Ansible info:
ansible 2.9.27
  config file = /home/glenn/ansible/ansible.cfg
  configured module search path = ['/home/glenn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 20 2022, 09:31:56) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]

Collection output:
    "item": {
        "filter_state": "present",
        "filter_type": "package_group",
        "name": "Package Groups",
        "repositories": [
            {
                "name": "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8",
                "product": "Red Hat Enterprise Linux for x86_64"
            }
        ],
        "rule_name": "Core"
    },
    "msg": "Found too many (2) results while searching for package_groups with name=\"Core\""
}

**Comment by evgeni** [comment]
Are you using the content view filter module, or the new content view filter rule one, that gives more flexibility for the rules?

**Comment by parmstro** [comment]
I think I see the problem @evgeni. The search scope is content view level rather than filter level which would restrict the visible repos. That should return a unique value. If the filter/search is not restricted by repository, the error will still occur as the underlying API requires a unique product+repository+package_group.

**Comment by parmstro** [comment]
I will create a test for this case.

**Comment by killroy1971** [comment]
The hammer command works, but I have to specify the Package Group's uuid along with the Package Group name.
As for the Ansible Collection, I'm using it as it comes out of the box. If it would help, let me know how to modify the Collection to use the other filter and I'll give it a try.

**Comment by parmstro** [comment]
@killroy1971 - yes, when you specify the uuid, you get to a unique object. I was trying to avoid having to ask for that, because its not easily knowable and is a pulp generated value, so it is not stable across multiple satellite implementations. If I allow you to send in the product and repository on the new filter rule interface, we can narrow the search and come back with a single package group. We can work on handling multiples, but then you basically get the choice of creating a rule for all of them or failing.

**Comment by Siddhu1096** [comment]
Guys! The only way I resolved it by integrating hammer command inside the playbook file. There is no other way;

**Comment by Siddhu1096** [comment]
But that was last year! I don't know if they have brought any changes to the module. Thanks!

**Comment by killroy1971** [comment]
The uuid may be necessary, as several Package Groups have the name in the BaseOS and AppStream repositories. When I have both repos in the filter, the error message lists 4 responses, not 2.

If the API call includes the uuid, would it be possible to use the unique uuids as part of the filter rule creation?

**Comment by killroy1971** [comment]
> 

I think it's worth a try. Package groups across multiple repositories is going to continue to be a problem, and a lot of users have fairly complex content filtering rules. For example, I have to call the role as a task so I can generated multiple rules from a list by looping over the role. Then I repeat that for each Filter that I create in a CV.

**Comment by killroy1971** [comment]
I commented out the following:
#    provisioner-secret:
#    controller-publish-secret:
#    node-publish-secret:
#    controller-expand-secret:

They were blank anyway.

Then I indented the node-db.node.session.auth items. I've seen plenty of kubernetes yaml that despite being indented when I wrote it, wasn't after being loaded into kubernetes. On the assumption that this was the case, I made this change as well.

Now everything installs....so far so good.

Thank you everyone for helping me with my values.yaml code.
